# Generated by Django 4.2.6 on 2023-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_num',
            field=models.PositiveIntegerField(verbose_name='Номер изображения'),
        ),
    ]
