# Generated by Django 4.2.6 on 2023-10-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('place', 'image')},
        ),
    ]
