# Generated by Django 4.2.6 on 2023-11-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_image_options_remove_place_description_long_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-place_id', 'image_num'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
