# Generated by Django 4.2.6 on 2023-11-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['place', 'image_num'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
