# Generated by Django 4.2.6 on 2023-11-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_alter_image_image_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_num',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Номер изображения'),
        ),
    ]
